
SERVER_STATUS = "UP"

def create_jira_ticket(
        title, 
        description=None):
    if not description:
        description = ("Auto-Generated by AI Agent")
    return {
        "ticket_id" : "JIRA-101",
        "description" : "CREATED",
        "title" : title,
        "description" : description
    }

def get_server_status(system):

    return {
        "system" : system,
        "status" : SERVER_STATUS
    }